# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ubuntu2004/workspace/CCU/Digital_Design/HW/HW03/DDLab_HW03.cache/wt [current_project]
set_property parent.project_path /home/ubuntu2004/workspace/CCU/Digital_Design/HW/HW03/DDLab_HW03.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ubuntu2004/workspace/CCU/Digital_Design/HW/HW03/DDLab_HW03.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/ubuntu2004/workspace/CCU/Digital_Design/HW/HW03/DDLab_HW03.srcs/sources_1/new/add4.v
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ubuntu2004/workspace/CCU/Digital_Design/HW/HW03/DDLab_HW03.srcs/constrs_1/imports/EX03/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files /home/ubuntu2004/workspace/CCU/Digital_Design/HW/HW03/DDLab_HW03.srcs/constrs_1/imports/EX03/Nexys-4-DDR-Master.xdc]


synth_design -top add -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef add.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file add_utilization_synth.rpt -pb add_utilization_synth.pb"
