USE `booking_record`;

-- Delete all rows for every tables.
DELETE FROM `Books`;
DELETE FROM `Customers`;
DELETE FROM `Orders`;

-- This is generated by ChatGPT.
INSERT INTO `Books` (`bid`, `btitle`, `author`, `year`, `price`) VALUES
(1, 'I am Cody 1', 'Cody', 1990, 10),
(2, 'I am Cody 2', 'Codey', 2000, 20),
(3, 'I am Cody 3', 'Codie', 1990, 30),
(4, 'I am Cody 4', 'Codi', 2000, 40),
(5, 'I am Cody 5', 'Codrick', 1990, 100),
(6, 'I am Co', 'Co', 1990, 150),
(7, 'I am not Cody', 'BCody', 2000, 200),
(8, 'I hate DB', 'William', 1990, 300),
(9, 'DB is horrible', 'Elizabeth', 2000, 450),
(10, 'What is MySQL', 'John', 2000, 500),
(11, 'What is PostgreSQL', 'Sarah', 1990, 550);

INSERT INTO `Customers` (`cid`, `cname`, `zipcode`) VALUES
(1,  'Alice Smith',     '12345'),
(2,  'Bob Johnson',     '23456'),
(3,  'Charlie Brown',   '02125'),
(4,  'David Lee',       '02125'),
(5,  'Emily Davis',     '56789'),
(6,  'Frank Hernandez', '12345'),
(7,  'Grace Kim',       '02125'),
(8,  'Henry Nguyen',    '89012'),
(9,  'Isabella Perez',  '90123'),
(10, 'Jack Taylor',     '02125');

INSERT INTO `Orders` (`cid`, `bid`, `quantity`) VALUES
(1, 1, 100),
(1, 3, 50),
(1, 5, 4),
(1, 7, 3),
(1, 9, 2),
(1, 11, 1),
(2, 1, 1),
(2, 5, 75),
(2, 7, 150),
(3, 1, 2),
(3, 9, 200),
(3, 2, 25),
(4, 4, 50),
(4, 6, 75),
(5, 1, 3),
(5, 8, 150),
(5, 10, 25),
(6, 1, 100),
(6, 6, 50),
(6, 8, 100),
(7, 10, 25),
(7, 4, 50),
(8, 1, 50),
(9, 1, 75),
(9, 2, 100),
(10, 9, 50),
(10, 11, 25);
