#include <stdio.h>
#include    "ExprLexer.h"
#include    "ExprParser.h"


// Main entry point for this example
//
int ANTLR3_CDECL
main	(int argc, char *argv[])
{
    pANTLR3_UINT8	    fName;

    pANTLR3_INPUT_STREAM    input;

    pExprLexer	    	    the_lexer;
    
    pExprParser             the_parser;

    pANTLR3_COMMON_TOKEN_STREAM	    tstream;

    pANTLR3_VECTOR the_all_tokens;

    int i;

    if (argc == 2 && argv[1] != NULL) {
    	fName = (pANTLR3_UINT8) argv[1];
    } else {
    	exit(1);
    }


    // Create the input stream using the supplied file name.
    input	= antlr3FileStreamNew(fName, ANTLR3_ENC_8BIT);

    if (input == 0) {
	fprintf(stderr, "Failed to open file %s\n", (char *)fName);
	exit(1);
    }

    the_lexer = ExprLexerNew(input);	    // ExprLexerNew is generated by ANTLR

    // Need to check for errors
    //
    if (the_lexer == NULL) {

	fprintf(stderr, "Unable to create the lexer due to malloc() failure1\n");
	exit(1);
    }

    tstream = antlr3CommonTokenStreamSourceNew(ANTLR3_SIZE_HINT, TOKENSOURCE(the_lexer));

    if (tstream == NULL) {
	fprintf(stderr, "Out of memory trying to allocate token stream\n");
	exit(1);
    }

    the_parser = ExprParserNew(tstream);

    if (the_parser == NULL) {
        fprintf(stderr, "Out of memory trying to allocate parser\n");
        exit(1);
    }

    the_parser->eval(the_parser);

    // We did not return anything from this parser rule, so we can finish. It only remains
    // to close down our open objects, in the reverse order we created them
    //
    the_parser->free(the_parser);
    tstream->free(tstream);	    //tstream = NULL;
    the_lexer->free(the_lexer);	    //lxr = NULL;
    input->close(input);	    //input = NULL;

    return 0;
}

